// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gWhTbede6s_UhOYBwradFX5k2eoqv_o',
    appId: '1:9259485102:web:c533308ce8dc8691b42a3f',
    messagingSenderId: '9259485102',
    projectId: 'appvocado-901b1',
    authDomain: 'appvocado-901b1.firebaseapp.com',
    storageBucket: 'appvocado-901b1.appspot.com',
    measurementId: 'G-DJP0CWX2NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKca4gwbDs3Es3xblv-T8LvY-SlE0awPw',
    appId: '1:9259485102:android:aad03ab9151066ffb42a3f',
    messagingSenderId: '9259485102',
    projectId: 'appvocado-901b1',
    storageBucket: 'appvocado-901b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3sQYMlTyts4ADfKoEeaOXlE5KrE5ROs',
    appId: '1:9259485102:ios:ffe8e59972a5b4a3b42a3f',
    messagingSenderId: '9259485102',
    projectId: 'appvocado-901b1',
    storageBucket: 'appvocado-901b1.appspot.com',
    iosClientId:
        '9259485102-j5i3shio77ig04oc665m0nsdjia8od0i.apps.googleusercontent.com',
    iosBundleId: 'com.appvocado.appvocado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3sQYMlTyts4ADfKoEeaOXlE5KrE5ROs',
    appId: '1:9259485102:ios:1b4bd1809971eddeb42a3f',
    messagingSenderId: '9259485102',
    projectId: 'appvocado-901b1',
    storageBucket: 'appvocado-901b1.appspot.com',
    iosClientId:
        '9259485102-cof1lt3lquoj1un5me6l2s69p10jam2g.apps.googleusercontent.com',
    iosBundleId: 'com.appvocado.appvocado.RunnerTests',
  );
}
